### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by ham3dt** [frejanordsiek/arduino_library_AD56X4#3]
Thanks for sharing this library, can you please add an simple example of setting/updating a single channel of DAC to an specific voltage?

**Comment by frejanordsiek** [comment]
I would have a hard time adding anything and knowing for sure that it is correct and works since I no longer have access to the hardware. It is really hard to further develop this package without it.

The example examples/Four_Sine_Waves/Four_Sine_Waves.ino does a little more than what you are looking for, but it should be sufficient.
